server:
  port: 8080

spring:
  application:
    name: searchable-example
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        type:
          descriptor:
            sql: trace
    hibernate:
      ddl-auto: create-drop
  main:
    allow-bean-definition-overriding: true
  h2:
    console:
      enabled: true
  devtools:
    restart:
      enabled: true
      poll-interval: 2s
      quiet-period: 1s

logging:
  level:
    root: INFO
    com.github.thkwag.searchable: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: DEBUG
    org.springframework.boot.devtools: DEBUG

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
    version: OPENAPI_3_0
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    config-url: /api-docs/swagger-config
    urls:
      - url: /api-docs
        name: API Documentation
  packages-to-scan: com.github.thkwag.searchable.example
  paths-to-match:
    - /api/**
    - /users/**
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  model-and-view-allowed: true
  auto-tag-classes: true
  writer-with-default-pretty-printer: true

searchable:
  swagger:
    enabled: true

debug: true 